# This workflow will install Python dependencies, run pre-commit checks and then run tests with a single version of Python

name: CI

on:
  push:
    branches: [ master ]
  pull_request_target:
    branches: [ master ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    name: Buidl and Test

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-versions: ${{ matrix.python-version }}

      - name: Enable cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.python-version }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Run pre-commit checks
        uses: pre-commit/action@v3.0.0

      - name: Run tests
        run: |
          pytest
